services:

  app:
    build:
      context: ./MonOpsX_app
    image: monopsx-app:1.0.0
    pull_policy: build
    restart: unless-stopped
    environment:
      CI: "1"
      EXPO_PUBLIC_API_URL: http://${HOST_IP:-localhost}:8000
      EXPO_NO_TELEMETRY: "1"
      REACT_NATIVE_PACKAGER_HOSTNAME: ${HOST_IP:-localhost}
    ports:
      - "8081:8081"
    depends_on:
      api:
        condition: service_started
